/* soapStub.h
   Generated by gSOAP 2.8.63 for baseService.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns2	"http://exception.blueant.axis.proventis.net/"
#define SOAP_NAMESPACE_OF_ns3	"http://base.blueant.axis.proventis.net/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20863
# error "GSOAP VERSION 20863 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumeration Types                                                          *
 *                                                                            *
\******************************************************************************/


/* baseService.h:143 */
#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean {
	xsd__boolean__false_ = 0,
	xsd__boolean__true_ = 1
};
#endif

/* baseService.h:216 */
#ifndef SOAP_TYPE_ns3__T_USCORELicenseType
#define SOAP_TYPE_ns3__T_USCORELicenseType (16)
/* ns3:T_LicenseType */
enum ns3__T_USCORELicenseType {
	ns3__T_USCORELicenseType__named = 0,
	ns3__T_USCORELicenseType__concurrent = 1
};
#endif

/* baseService.h:234 */
#ifndef SOAP_TYPE_ns3__T_USCOREUserState
#define SOAP_TYPE_ns3__T_USCOREUserState (17)
/* ns3:T_UserState */
enum ns3__T_USCOREUserState {
	ns3__T_USCOREUserState__active = 0,
	ns3__T_USCOREUserState__locked = 1
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct ns2__GeneralWebserviceException;	/* baseService.h:295 */
struct ns3__T_USCOREForeignKey;	/* baseService.h:323 */
struct ns3__T_USCOREForeignKeyList;	/* baseService.h:346 */
union _ns3__union_UserIDInfo;	/* baseService.h:381 */
struct ns3__UserIDInfo;	/* baseService.h:363 */
struct ns3__T_USCOREUser;	/* baseService.h:395 */
struct ns3__T_USCOREIdList;	/* baseService.h:415 */
struct _ns3__session;	/* baseService.h:481 */
struct _ns3__LoginRequestParameter;	/* baseService.h:499 */
struct _ns3__LoginNoAuthRequestParameter;	/* baseService.h:517 */
struct _ns3__LoginSAMLRequestParameter;	/* baseService.h:533 */
union _ns3__union_LoginImpersonateRequestParameter;	/* baseService.h:576 */
struct _ns3__LoginImpersonateRequestParameter;	/* baseService.h:549 */
struct _ns3__LogoutRequestParameter;	/* baseService.h:591 */
struct _ns3__createUserRequestParameter;	/* baseService.h:607 */
struct _ns3__searchUserRequestParameter;	/* baseService.h:665 */
struct _ns3__deleteUserRequestParameter;	/* baseService.h:731 */
struct _ns3__UserList;	/* baseService.h:749 */
struct ns2__UserManagementException;	/* baseService.h:766 */
struct _ns2__WeekFinishedException;	/* baseService.h:786 */
struct _ns2__InvalidParameterException;	/* baseService.h:806 */
struct _ns2__AssertionException;	/* baseService.h:826 */
struct _ns2__GeneralWebserviceException;	/* baseService.h:846 */
struct ns2__InvalidLicenseException;	/* baseService.h:865 */
struct _ns2__InvalidSessionException;	/* baseService.h:887 */
struct _ns2__InvalidClientException;	/* baseService.h:909 */
struct _ns2__PermissionDeniedException;	/* baseService.h:931 */
struct _ns2__InvalidUsernamePasswordCombinationException;	/* baseService.h:953 */
struct _ns2__InvalidUsernameException;	/* baseService.h:975 */
struct _ns2__InvalidDatesException;	/* baseService.h:997 */
struct _ns2__ServerMaintenanceException;	/* baseService.h:1019 */
struct _ns2__ImpersonatedUserNotFoundException;	/* baseService.h:1041 */
struct _ns2__InvalidNrOfImpersonationsException;	/* baseService.h:1063 */
struct _ns2__InvalidNamedLicenseException;	/* baseService.h:1085 */
struct _ns2__InvalidConcurrentLicenseException;	/* baseService.h:1109 */
struct __ns1__Login;	/* baseService.h:1422 */
struct __ns1__LoginNoAuth;	/* baseService.h:1499 */
struct __ns1__LoginSAML;	/* baseService.h:1576 */
struct __ns1__LoginImpersonate;	/* baseService.h:1659 */
struct __ns1__LogoutResponse;	/* baseService.h:1670 */
struct __ns1__Logout;	/* baseService.h:1734 */
struct __ns1__createUser;	/* baseService.h:1812 */
struct __ns1__deleteUserResponse;	/* baseService.h:1823 */
struct __ns1__deleteUser;	/* baseService.h:1893 */
struct __ns1__searchUser;	/* baseService.h:1971 */

/* baseService.h:295 */
#ifndef SOAP_TYPE_ns2__GeneralWebserviceException
#define SOAP_TYPE_ns2__GeneralWebserviceException (18)
/* complex XSD type 'ns2:GeneralWebserviceException': */
struct ns2__GeneralWebserviceException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:323 */
#ifndef SOAP_TYPE_ns3__T_USCOREForeignKey
#define SOAP_TYPE_ns3__T_USCOREForeignKey (19)
/* complex XSD type 'ns3:T_ForeignKey': */
struct ns3__T_USCOREForeignKey {
        /** Required nillable (xsi:nil when NULL) element 'ns3:foreignID' of XSD type 'xsd:string' */
        char *foreignID;
        /** Required nillable (xsi:nil when NULL) element 'ns3:foreignSystem' of XSD type 'xsd:string' */
        char *foreignSystem;
};
#endif

/* baseService.h:346 */
#ifndef SOAP_TYPE_ns3__T_USCOREForeignKeyList
#define SOAP_TYPE_ns3__T_USCOREForeignKeyList (20)
/* complex XSD type 'ns3:T_ForeignKeyList': */
struct ns3__T_USCOREForeignKeyList {
        /** Sequence of elements 'ns3:ForeignKey' of XSD type 'ns3:T_ForeignKey' stored in dynamic array ForeignKey_ of length __sizeForeignKey */
        int __sizeForeignKey;
        struct ns3__T_USCOREForeignKey *ForeignKey_;
};
#endif

/* baseService.h:381 */
#ifndef SOAP_TYPE__ns3__union_UserIDInfo
#define SOAP_TYPE__ns3__union_UserIDInfo (23)
/* union serializable only when used as a member of a struct or class with a union variant selector */
union _ns3__union_UserIDInfo
{
        #define SOAP_UNION__ns3__union_UserIDInfo_userID	(1)	/**< union variant selector value for member userID */
        LONG64 userID;
        #define SOAP_UNION__ns3__union_UserIDInfo_userName	(2)	/**< union variant selector value for member userName */
        char *userName;
};
#endif

/* baseService.h:363 */
#ifndef SOAP_TYPE_ns3__UserIDInfo
#define SOAP_TYPE_ns3__UserIDInfo (22)
/* Choice: */
struct ns3__UserIDInfo {
        /** Union with union _ns3__union_UserIDInfo variant selector __union_UserIDInfo set to one of: SOAP_UNION__ns3__union_UserIDInfo_userID SOAP_UNION__ns3__union_UserIDInfo_userName */
        int __union_UserIDInfo;
        union _ns3__union_UserIDInfo union_UserIDInfo;
};
#endif

/* baseService.h:395 */
#ifndef SOAP_TYPE_ns3__T_USCOREUser
#define SOAP_TYPE_ns3__T_USCOREUser (24)
/* complex XSD type 'ns3:T_User': */
struct ns3__T_USCOREUser {
        /** Required element 'ns3:userID' of XSD type 'ns3:id' */
        LONG64 userID;
        /** Required element 'ns3:personID' of XSD type 'ns3:id' */
        LONG64 personID;
        /** Required element 'ns3:username' of XSD type 'xsd:string' */
        char *username;
        /** Required element 'ns3:permissionGroups' of XSD type 'ns3:T_IdList' */
        struct ns3__T_USCOREIdList *permissionGroups;
        /** Required element 'ns3:lastname' of XSD type 'xsd:string' */
        char *lastname;
        /** Required element 'ns3:firstname' of XSD type 'xsd:string' */
        char *firstname;
        /** Required element 'ns3:personalNumber' of XSD type 'xsd:string' */
        char *personalNumber;
        /** Required nillable (xsi:nil when NULL) element 'ns3:email' of XSD type 'xsd:string' */
        char *email;
        /** Required element 'ns3:licenseType' of XSD type 'ns3:T_LicenseType' */
        enum ns3__T_USCORELicenseType licenseType;
        /** Required element 'ns3:userState' of XSD type 'ns3:T_UserState' */
        enum ns3__T_USCOREUserState userState;
        /** Required nillable (xsi:nil when NULL) element 'ns3:foreignKeyList' of XSD type 'ns3:T_ForeignKeyList' */
        struct ns3__T_USCOREForeignKeyList *foreignKeyList;
};
#endif

/* baseService.h:415 */
#ifndef SOAP_TYPE_ns3__T_USCOREIdList
#define SOAP_TYPE_ns3__T_USCOREIdList (25)
/* complex XSD type 'ns3:T_IdList': */
struct ns3__T_USCOREIdList {
        /** Sequence of elements 'ns3:ID' of XSD type 'ns3:id' stored in dynamic array ID_ of length __sizeID */
        int __sizeID;
        LONG64 *ID_;
};
#endif

/* baseService.h:481 */
#ifndef SOAP_TYPE__ns3__session
#define SOAP_TYPE__ns3__session (29)
/* complex XSD type 'ns3:session': */
struct _ns3__session {
        /** Required element 'ns3:sessionID' of XSD type 'xsd:string' */
        char *sessionID;
        /** Required element 'ns3:personID' of XSD type 'xsd:long' */
        LONG64 personID;
};
#endif

/* baseService.h:499 */
#ifndef SOAP_TYPE__ns3__LoginRequestParameter
#define SOAP_TYPE__ns3__LoginRequestParameter (30)
/* complex XSD type 'ns3:LoginRequestParameter': */
struct _ns3__LoginRequestParameter {
        /** Required element 'ns3:username' of XSD type 'xsd:string' */
        char *username;
        /** Required element 'ns3:password' of XSD type 'xsd:string' */
        char *password;
};
#endif

/* baseService.h:517 */
#ifndef SOAP_TYPE__ns3__LoginNoAuthRequestParameter
#define SOAP_TYPE__ns3__LoginNoAuthRequestParameter (31)
/* complex XSD type 'ns3:LoginNoAuthRequestParameter': */
struct _ns3__LoginNoAuthRequestParameter {
        /** Required element 'ns3:username' of XSD type 'xsd:string' */
        char *username;
};
#endif

/* baseService.h:533 */
#ifndef SOAP_TYPE__ns3__LoginSAMLRequestParameter
#define SOAP_TYPE__ns3__LoginSAMLRequestParameter (32)
/* complex XSD type 'ns3:LoginSAMLRequestParameter': */
struct _ns3__LoginSAMLRequestParameter {
        /** Required element 'ns3:SAMLartifact' of XSD type 'xsd:string' */
        char *SAMLartifact;
};
#endif

/* baseService.h:576 */
#ifndef SOAP_TYPE__ns3__union_LoginImpersonateRequestParameter
#define SOAP_TYPE__ns3__union_LoginImpersonateRequestParameter (34)
/* union serializable only when used as a member of a struct or class with a union variant selector */
union _ns3__union_LoginImpersonateRequestParameter
{
        #define SOAP_UNION__ns3__union_LoginImpersonateRequestParameter_ImpersonateUsername	(1)	/**< union variant selector value for member ImpersonateUsername */
        char *ImpersonateUsername;
        #define SOAP_UNION__ns3__union_LoginImpersonateRequestParameter_ImpersonateUserID	(2)	/**< union variant selector value for member ImpersonateUserID */
        LONG64 *ImpersonateUserID;
        #define SOAP_UNION__ns3__union_LoginImpersonateRequestParameter_ImpersonateForeignKey	(3)	/**< union variant selector value for member ImpersonateForeignKey */
        struct ns3__T_USCOREForeignKey *ImpersonateForeignKey;
};
#endif

/* baseService.h:549 */
#ifndef SOAP_TYPE__ns3__LoginImpersonateRequestParameter
#define SOAP_TYPE__ns3__LoginImpersonateRequestParameter (33)
/* complex XSD type 'ns3:LoginImpersonateRequestParameter': */
struct _ns3__LoginImpersonateRequestParameter {
        /** Required element 'ns3:username' of XSD type 'xsd:string' */
        char *username;
        /** Required element 'ns3:password' of XSD type 'xsd:string' */
        char *password;
        /** Union with union _ns3__union_LoginImpersonateRequestParameter variant selector __union_LoginImpersonateRequestParameter set to one of: SOAP_UNION__ns3__union_LoginImpersonateRequestParameter_ImpersonateUsername SOAP_UNION__ns3__union_LoginImpersonateRequestParameter_ImpersonateUserID SOAP_UNION__ns3__union_LoginImpersonateRequestParameter_ImpersonateForeignKey */
        int __union_LoginImpersonateRequestParameter;
        union _ns3__union_LoginImpersonateRequestParameter union_LoginImpersonateRequestParameter;
};
#endif

/* baseService.h:591 */
#ifndef SOAP_TYPE__ns3__LogoutRequestParameter
#define SOAP_TYPE__ns3__LogoutRequestParameter (35)
/* complex XSD type 'ns3:LogoutRequestParameter': */
struct _ns3__LogoutRequestParameter {
        /** Required element 'ns3:sessionID' of XSD type 'xsd:string' */
        char *sessionID;
};
#endif

/* baseService.h:607 */
#ifndef SOAP_TYPE__ns3__createUserRequestParameter
#define SOAP_TYPE__ns3__createUserRequestParameter (36)
/* complex XSD type 'ns3:createUserRequestParameter': */
struct _ns3__createUserRequestParameter {
        /** Required element 'ns3:sessionID' of XSD type 'xsd:string' */
        char *sessionID;
        /** Required element 'ns3:personID' of XSD type 'ns3:id' */
        LONG64 personID;
        /** Required element 'ns3:username' of XSD type 'xsd:string' */
        char *username;
        /** Required nillable (xsi:nil when NULL) element 'ns3:passwort' of XSD type 'xsd:string' */
        char *passwort;
        /** Required nillable (xsi:nil when NULL) element 'ns3:permissionGroups' of XSD type 'ns3:T_IdList' */
        struct ns3__T_USCOREIdList *permissionGroups;
        /** Required nillable (xsi:nil when NULL) element 'ns3:accessFrom' of XSD type 'xsd:date' */
        char *accessFrom;
        /** Required nillable (xsi:nil when NULL) element 'ns3:accessTo' of XSD type 'xsd:date' */
        char *accessTo;
        /** Required nillable (xsi:nil when NULL) element 'ns3:licenseType' of XSD type 'ns3:T_LicenseType' */
        enum ns3__T_USCORELicenseType *licenseType;
        /** Required nillable (xsi:nil when NULL) element 'ns3:foreignKeyList' of XSD type 'ns3:T_ForeignKeyList' */
        struct ns3__T_USCOREForeignKeyList *foreignKeyList;
};
#endif

/* baseService.h:665 */
#ifndef SOAP_TYPE__ns3__searchUserRequestParameter
#define SOAP_TYPE__ns3__searchUserRequestParameter (38)
/* complex XSD type 'ns3:searchUserRequestParameter': */
struct _ns3__searchUserRequestParameter {
        /** Required element 'ns3:sessionID' of XSD type 'xsd:string' */
        char *sessionID;
        /** Required nillable (xsi:nil when NULL) element 'ns3:username' of XSD type 'xsd:string' */
        char *username;
        /** Required nillable (xsi:nil when NULL) element 'ns3:email' of XSD type 'xsd:string' */
        char *email;
        /** Required nillable (xsi:nil when NULL) element 'ns3:personID' of XSD type 'ns3:id' */
        LONG64 *personID;
        /** Required nillable (xsi:nil when NULL) element 'ns3:permissionGroupID' of XSD type 'ns3:id' */
        LONG64 *permissionGroupID;
        /** Required nillable (xsi:nil when NULL) element 'ns3:firstname' of XSD type 'xsd:string' */
        char *firstname;
        /** Required nillable (xsi:nil when NULL) element 'ns3:lastname' of XSD type 'xsd:string' */
        char *lastname;
        /** Required nillable (xsi:nil when NULL) element 'ns3:personalNumber' of XSD type 'xsd:string' */
        char *personalNumber;
        /** Required nillable (xsi:nil when NULL) element 'ns3:licenseType' of XSD type 'ns3:T_LicenseType' */
        enum ns3__T_USCORELicenseType *licenseType;
        /** Required nillable (xsi:nil when NULL) element 'ns3:userState' of XSD type 'ns3:T_UserState' */
        enum ns3__T_USCOREUserState *userState;
        /** Required nillable (xsi:nil when NULL) element 'ns3:foreignKey' of XSD type 'ns3:T_ForeignKey' */
        struct ns3__T_USCOREForeignKey *foreignKey;
};
#endif

/* baseService.h:731 */
#ifndef SOAP_TYPE__ns3__deleteUserRequestParameter
#define SOAP_TYPE__ns3__deleteUserRequestParameter (40)
/* complex XSD type 'ns3:deleteUserRequestParameter': */
struct _ns3__deleteUserRequestParameter {
        /** Required element 'ns3:sessionID' of XSD type 'xsd:string' */
        char *sessionID;
        /** Required element 'ns3:user' of XSD type 'ns3:UserIDInfo' */
        struct ns3__UserIDInfo *user;
};
#endif

/* baseService.h:749 */
#ifndef SOAP_TYPE__ns3__UserList
#define SOAP_TYPE__ns3__UserList (42)
/* complex XSD type 'ns3:UserList': */
struct _ns3__UserList {
        /** Sequence of elements 'ns3:User' of XSD type 'ns3:T_User' stored in dynamic array User_ of length __sizeUser */
        int __sizeUser;
        struct ns3__T_USCOREUser *User_;
};
#endif

/* baseService.h:766 */
#ifndef SOAP_TYPE_ns2__UserManagementException
#define SOAP_TYPE_ns2__UserManagementException (44)
/* complex XSD type 'ns2:UserManagementException': */
struct ns2__UserManagementException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:786 */
#ifndef SOAP_TYPE__ns2__WeekFinishedException
#define SOAP_TYPE__ns2__WeekFinishedException (45)
/* complex XSD type 'ns2:WeekFinishedException': */
struct _ns2__WeekFinishedException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:806 */
#ifndef SOAP_TYPE__ns2__InvalidParameterException
#define SOAP_TYPE__ns2__InvalidParameterException (46)
/* complex XSD type 'ns2:InvalidParameterException': */
struct _ns2__InvalidParameterException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:826 */
#ifndef SOAP_TYPE__ns2__AssertionException
#define SOAP_TYPE__ns2__AssertionException (47)
/* complex XSD type 'ns2:AssertionException': */
struct _ns2__AssertionException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:846 */
#ifndef SOAP_TYPE__ns2__GeneralWebserviceException
#define SOAP_TYPE__ns2__GeneralWebserviceException (48)
/* complex XSD type 'ns2:GeneralWebserviceException': */
struct _ns2__GeneralWebserviceException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:865 */
#ifndef SOAP_TYPE_ns2__InvalidLicenseException
#define SOAP_TYPE_ns2__InvalidLicenseException (49)
/* complex XSD type 'ns2:InvalidLicenseException': */
struct ns2__InvalidLicenseException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:887 */
#ifndef SOAP_TYPE__ns2__InvalidSessionException
#define SOAP_TYPE__ns2__InvalidSessionException (50)
/* complex XSD type 'ns2:InvalidSessionException': */
struct _ns2__InvalidSessionException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:909 */
#ifndef SOAP_TYPE__ns2__InvalidClientException
#define SOAP_TYPE__ns2__InvalidClientException (51)
/* complex XSD type 'ns2:InvalidClientException': */
struct _ns2__InvalidClientException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:931 */
#ifndef SOAP_TYPE__ns2__PermissionDeniedException
#define SOAP_TYPE__ns2__PermissionDeniedException (52)
/* complex XSD type 'ns2:PermissionDeniedException': */
struct _ns2__PermissionDeniedException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:953 */
#ifndef SOAP_TYPE__ns2__InvalidUsernamePasswordCombinationException
#define SOAP_TYPE__ns2__InvalidUsernamePasswordCombinationException (53)
/* complex XSD type 'ns2:InvalidUsernamePasswordCombinationException': */
struct _ns2__InvalidUsernamePasswordCombinationException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:975 */
#ifndef SOAP_TYPE__ns2__InvalidUsernameException
#define SOAP_TYPE__ns2__InvalidUsernameException (54)
/* complex XSD type 'ns2:InvalidUsernameException': */
struct _ns2__InvalidUsernameException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:997 */
#ifndef SOAP_TYPE__ns2__InvalidDatesException
#define SOAP_TYPE__ns2__InvalidDatesException (55)
/* complex XSD type 'ns2:InvalidDatesException': */
struct _ns2__InvalidDatesException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:1019 */
#ifndef SOAP_TYPE__ns2__ServerMaintenanceException
#define SOAP_TYPE__ns2__ServerMaintenanceException (56)
/* complex XSD type 'ns2:ServerMaintenanceException': */
struct _ns2__ServerMaintenanceException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:1041 */
#ifndef SOAP_TYPE__ns2__ImpersonatedUserNotFoundException
#define SOAP_TYPE__ns2__ImpersonatedUserNotFoundException (57)
/* complex XSD type 'ns2:ImpersonatedUserNotFoundException': */
struct _ns2__ImpersonatedUserNotFoundException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:1063 */
#ifndef SOAP_TYPE__ns2__InvalidNrOfImpersonationsException
#define SOAP_TYPE__ns2__InvalidNrOfImpersonationsException (58)
/* complex XSD type 'ns2:InvalidNrOfImpersonationsException': */
struct _ns2__InvalidNrOfImpersonationsException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:1085 */
#ifndef SOAP_TYPE__ns2__InvalidNamedLicenseException
#define SOAP_TYPE__ns2__InvalidNamedLicenseException (59)
/* complex XSD type 'ns2:InvalidNamedLicenseException': */
struct _ns2__InvalidNamedLicenseException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:1109 */
#ifndef SOAP_TYPE__ns2__InvalidConcurrentLicenseException
#define SOAP_TYPE__ns2__InvalidConcurrentLicenseException (60)
/* complex XSD type 'ns2:InvalidConcurrentLicenseException': */
struct _ns2__InvalidConcurrentLicenseException {
        /** Required nillable (xsi:nil when NULL) element 'ns2:cause' of XSD type 'xsd:anyType' */
        char *cause;
        /** Required nillable (xsi:nil when NULL) element 'ns2:message' of XSD type 'xsd:string' */
        char *message;
};
#endif

/* baseService.h:1303 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (61)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        /** Optional element 'ns2:AssertionException' of XSD type 'ns2:AssertionException' */
        struct _ns2__AssertionException *ns2__AssertionException;
        /** Optional element 'ns2:GeneralWebserviceException' of XSD type 'ns2:GeneralWebserviceException' */
        struct _ns2__GeneralWebserviceException *ns2__GeneralWebserviceException;
        /** Optional element 'ns2:ImpersonatedUserNotFoundException' of XSD type 'ns2:ImpersonatedUserNotFoundException' */
        struct _ns2__ImpersonatedUserNotFoundException *ns2__ImpersonatedUserNotFoundException;
        /** Optional element 'ns2:InvalidClientException' of XSD type 'ns2:InvalidClientException' */
        struct _ns2__InvalidClientException *ns2__InvalidClientException;
        /** Optional element 'ns2:InvalidConcurrentLicenseException' of XSD type 'ns2:InvalidConcurrentLicenseException' */
        struct _ns2__InvalidConcurrentLicenseException *ns2__InvalidConcurrentLicenseException;
        /** Optional element 'ns2:InvalidDatesException' of XSD type 'ns2:InvalidDatesException' */
        struct _ns2__InvalidDatesException *ns2__InvalidDatesException;
        /** Optional element 'ns2:InvalidNamedLicenseException' of XSD type 'ns2:InvalidNamedLicenseException' */
        struct _ns2__InvalidNamedLicenseException *ns2__InvalidNamedLicenseException;
        /** Optional element 'ns2:InvalidNrOfImpersonationsException' of XSD type 'ns2:InvalidNrOfImpersonationsException' */
        struct _ns2__InvalidNrOfImpersonationsException *ns2__InvalidNrOfImpersonationsException;
        /** Optional element 'ns2:InvalidParameterException' of XSD type 'ns2:InvalidParameterException' */
        struct _ns2__InvalidParameterException *ns2__InvalidParameterException;
        /** Optional element 'ns2:InvalidSessionException' of XSD type 'ns2:InvalidSessionException' */
        struct _ns2__InvalidSessionException *ns2__InvalidSessionException;
        /** Optional element 'ns2:InvalidUsernameException' of XSD type 'ns2:InvalidUsernameException' */
        struct _ns2__InvalidUsernameException *ns2__InvalidUsernameException;
        /** Optional element 'ns2:InvalidUsernamePasswordCombinationException' of XSD type 'ns2:InvalidUsernamePasswordCombinationException' */
        struct _ns2__InvalidUsernamePasswordCombinationException *ns2__InvalidUsernamePasswordCombinationException;
        /** Optional element 'ns2:PermissionDeniedException' of XSD type 'ns2:PermissionDeniedException' */
        struct _ns2__PermissionDeniedException *ns2__PermissionDeniedException;
        /** Optional element 'ns2:ServerMaintenanceException' of XSD type 'ns2:ServerMaintenanceException' */
        struct _ns2__ServerMaintenanceException *ns2__ServerMaintenanceException;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
        char *__any;
};
#endif
#endif

/* baseService.h:1422 */
#ifndef SOAP_TYPE___ns1__Login
#define SOAP_TYPE___ns1__Login (81)
/* Wrapper: */
struct __ns1__Login {
        /** Optional element 'ns3:LoginRequestParameter' of XSD type 'ns3:LoginRequestParameter' */
        struct _ns3__LoginRequestParameter *ns3__LoginRequestParameter;
};
#endif

/* baseService.h:1499 */
#ifndef SOAP_TYPE___ns1__LoginNoAuth
#define SOAP_TYPE___ns1__LoginNoAuth (84)
/* Wrapper: */
struct __ns1__LoginNoAuth {
        /** Optional element 'ns3:LoginNoAuthRequestParameter' of XSD type 'ns3:LoginNoAuthRequestParameter' */
        struct _ns3__LoginNoAuthRequestParameter *ns3__LoginNoAuthRequestParameter;
};
#endif

/* baseService.h:1576 */
#ifndef SOAP_TYPE___ns1__LoginSAML
#define SOAP_TYPE___ns1__LoginSAML (87)
/* Wrapper: */
struct __ns1__LoginSAML {
        /** Optional element 'ns3:LoginSAMLRequestParameter' of XSD type 'ns3:LoginSAMLRequestParameter' */
        struct _ns3__LoginSAMLRequestParameter *ns3__LoginSAMLRequestParameter;
};
#endif

/* baseService.h:1659 */
#ifndef SOAP_TYPE___ns1__LoginImpersonate
#define SOAP_TYPE___ns1__LoginImpersonate (90)
/* Wrapper: */
struct __ns1__LoginImpersonate {
        /** Optional element 'ns3:LoginImpersonateRequestParameter' of XSD type 'ns3:LoginImpersonateRequestParameter' */
        struct _ns3__LoginImpersonateRequestParameter *ns3__LoginImpersonateRequestParameter;
};
#endif

/* baseService.h:1670 */
#ifndef SOAP_TYPE___ns1__LogoutResponse
#define SOAP_TYPE___ns1__LogoutResponse (91)
/* Wrapper: */
struct __ns1__LogoutResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* baseService.h:1734 */
#ifndef SOAP_TYPE___ns1__Logout
#define SOAP_TYPE___ns1__Logout (95)
/* Wrapper: */
struct __ns1__Logout {
        /** Optional element 'ns3:LogoutRequestParameter' of XSD type 'ns3:LogoutRequestParameter' */
        struct _ns3__LogoutRequestParameter *ns3__LogoutRequestParameter;
};
#endif

/* baseService.h:1812 */
#ifndef SOAP_TYPE___ns1__createUser
#define SOAP_TYPE___ns1__createUser (98)
/* Wrapper: */
struct __ns1__createUser {
        /** Optional element 'ns3:createUserRequestParameter' of XSD type 'ns3:createUserRequestParameter' */
        struct _ns3__createUserRequestParameter *ns3__createUserRequestParameter;
};
#endif

/* baseService.h:1823 */
#ifndef SOAP_TYPE___ns1__deleteUserResponse
#define SOAP_TYPE___ns1__deleteUserResponse (99)
/* Wrapper: */
struct __ns1__deleteUserResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* baseService.h:1893 */
#ifndef SOAP_TYPE___ns1__deleteUser
#define SOAP_TYPE___ns1__deleteUser (103)
/* Wrapper: */
struct __ns1__deleteUser {
        /** Optional element 'ns3:deleteUserRequestParameter' of XSD type 'ns3:deleteUserRequestParameter' */
        struct _ns3__deleteUserRequestParameter *ns3__deleteUserRequestParameter;
};
#endif

/* baseService.h:1971 */
#ifndef SOAP_TYPE___ns1__searchUser
#define SOAP_TYPE___ns1__searchUser (107)
/* Wrapper: */
struct __ns1__searchUser {
        /** Optional element 'ns3:searchUserRequestParameter' of XSD type 'ns3:searchUserRequestParameter' */
        struct _ns3__searchUserRequestParameter *ns3__searchUserRequestParameter;
};
#endif

/* baseService.h:2433 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (108)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* baseService.h:2433 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (109)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* baseService.h:2433 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (111)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* baseService.h:2433 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (112)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/* baseService.h:146 */
#ifndef SOAP_TYPE_xsd__date
#define SOAP_TYPE_xsd__date (8)
typedef char *xsd__date;
#endif

/* baseService.h:191 */
#ifndef SOAP_TYPE_ns3__id
#define SOAP_TYPE_ns3__id (10)
typedef LONG64 ns3__id;
#endif

/* baseService.h:195 */
#ifndef SOAP_TYPE_ns3__optionalInt
#define SOAP_TYPE_ns3__optionalInt (11)
typedef int ns3__optionalInt;
#endif

/* baseService.h:199 */
#ifndef SOAP_TYPE_ns3__optionalBoolean
#define SOAP_TYPE_ns3__optionalBoolean (12)
typedef enum xsd__boolean ns3__optionalBoolean;
#endif

/* baseService.h:203 */
#ifndef SOAP_TYPE_ns3__optionalDouble
#define SOAP_TYPE_ns3__optionalDouble (14)
typedef double ns3__optionalDouble;
#endif

/* baseService.h:207 */
#ifndef SOAP_TYPE_ns3__optionalLong
#define SOAP_TYPE_ns3__optionalLong (15)
typedef LONG64 ns3__optionalLong;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* ns3__optionalInt has binding name 'ns3__optionalInt' for type 'ns3:optionalInt' */
#ifndef SOAP_TYPE_ns3__optionalInt
#define SOAP_TYPE_ns3__optionalInt (11)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* ns3__optionalLong has binding name 'ns3__optionalLong' for type 'ns3:optionalLong' */
#ifndef SOAP_TYPE_ns3__optionalLong
#define SOAP_TYPE_ns3__optionalLong (15)
#endif

/* ns3__id has binding name 'ns3__id' for type 'ns3:id' */
#ifndef SOAP_TYPE_ns3__id
#define SOAP_TYPE_ns3__id (10)
#endif

/* LONG64 has binding name 'LONG64' for type 'xsd:long' */
#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (9)
#endif

/* ns3__optionalDouble has binding name 'ns3__optionalDouble' for type 'ns3:optionalDouble' */
#ifndef SOAP_TYPE_ns3__optionalDouble
#define SOAP_TYPE_ns3__optionalDouble (14)
#endif

/* double has binding name 'double' for type 'xsd:double' */
#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (13)
#endif

/* enum ns3__T_USCOREUserState has binding name 'ns3__T_USCOREUserState' for type 'ns3:T_UserState' */
#ifndef SOAP_TYPE_ns3__T_USCOREUserState
#define SOAP_TYPE_ns3__T_USCOREUserState (17)
#endif

/* enum ns3__T_USCORELicenseType has binding name 'ns3__T_USCORELicenseType' for type 'ns3:T_LicenseType' */
#ifndef SOAP_TYPE_ns3__T_USCORELicenseType
#define SOAP_TYPE_ns3__T_USCORELicenseType (16)
#endif

/* ns3__optionalBoolean has binding name 'ns3__optionalBoolean' for type 'ns3:optionalBoolean' */
#ifndef SOAP_TYPE_ns3__optionalBoolean
#define SOAP_TYPE_ns3__optionalBoolean (12)
#endif

/* enum xsd__boolean has binding name 'xsd__boolean' for type 'xsd:boolean' */
#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (112)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (111)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (109)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (108)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (61)
#endif

/* struct _ns2__InvalidConcurrentLicenseException has binding name '_ns2__InvalidConcurrentLicenseException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidConcurrentLicenseException
#define SOAP_TYPE__ns2__InvalidConcurrentLicenseException (60)
#endif

/* struct _ns2__InvalidNamedLicenseException has binding name '_ns2__InvalidNamedLicenseException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidNamedLicenseException
#define SOAP_TYPE__ns2__InvalidNamedLicenseException (59)
#endif

/* struct _ns2__InvalidNrOfImpersonationsException has binding name '_ns2__InvalidNrOfImpersonationsException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidNrOfImpersonationsException
#define SOAP_TYPE__ns2__InvalidNrOfImpersonationsException (58)
#endif

/* struct _ns2__ImpersonatedUserNotFoundException has binding name '_ns2__ImpersonatedUserNotFoundException' for type '' */
#ifndef SOAP_TYPE__ns2__ImpersonatedUserNotFoundException
#define SOAP_TYPE__ns2__ImpersonatedUserNotFoundException (57)
#endif

/* struct _ns2__ServerMaintenanceException has binding name '_ns2__ServerMaintenanceException' for type '' */
#ifndef SOAP_TYPE__ns2__ServerMaintenanceException
#define SOAP_TYPE__ns2__ServerMaintenanceException (56)
#endif

/* struct _ns2__InvalidDatesException has binding name '_ns2__InvalidDatesException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidDatesException
#define SOAP_TYPE__ns2__InvalidDatesException (55)
#endif

/* struct _ns2__InvalidUsernameException has binding name '_ns2__InvalidUsernameException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidUsernameException
#define SOAP_TYPE__ns2__InvalidUsernameException (54)
#endif

/* struct _ns2__InvalidUsernamePasswordCombinationException has binding name '_ns2__InvalidUsernamePasswordCombinationException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidUsernamePasswordCombinationException
#define SOAP_TYPE__ns2__InvalidUsernamePasswordCombinationException (53)
#endif

/* struct _ns2__PermissionDeniedException has binding name '_ns2__PermissionDeniedException' for type '' */
#ifndef SOAP_TYPE__ns2__PermissionDeniedException
#define SOAP_TYPE__ns2__PermissionDeniedException (52)
#endif

/* struct _ns2__InvalidClientException has binding name '_ns2__InvalidClientException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidClientException
#define SOAP_TYPE__ns2__InvalidClientException (51)
#endif

/* struct _ns2__InvalidSessionException has binding name '_ns2__InvalidSessionException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidSessionException
#define SOAP_TYPE__ns2__InvalidSessionException (50)
#endif

/* struct ns2__InvalidLicenseException has binding name 'ns2__InvalidLicenseException' for type 'ns2:InvalidLicenseException' */
#ifndef SOAP_TYPE_ns2__InvalidLicenseException
#define SOAP_TYPE_ns2__InvalidLicenseException (49)
#endif

/* struct _ns2__GeneralWebserviceException has binding name '_ns2__GeneralWebserviceException' for type '' */
#ifndef SOAP_TYPE__ns2__GeneralWebserviceException
#define SOAP_TYPE__ns2__GeneralWebserviceException (48)
#endif

/* struct _ns2__AssertionException has binding name '_ns2__AssertionException' for type '' */
#ifndef SOAP_TYPE__ns2__AssertionException
#define SOAP_TYPE__ns2__AssertionException (47)
#endif

/* struct _ns2__InvalidParameterException has binding name '_ns2__InvalidParameterException' for type '' */
#ifndef SOAP_TYPE__ns2__InvalidParameterException
#define SOAP_TYPE__ns2__InvalidParameterException (46)
#endif

/* struct _ns2__WeekFinishedException has binding name '_ns2__WeekFinishedException' for type '' */
#ifndef SOAP_TYPE__ns2__WeekFinishedException
#define SOAP_TYPE__ns2__WeekFinishedException (45)
#endif

/* struct ns2__UserManagementException has binding name 'ns2__UserManagementException' for type 'ns2:UserManagementException' */
#ifndef SOAP_TYPE_ns2__UserManagementException
#define SOAP_TYPE_ns2__UserManagementException (44)
#endif

/* struct _ns3__UserList has binding name '_ns3__UserList' for type '' */
#ifndef SOAP_TYPE__ns3__UserList
#define SOAP_TYPE__ns3__UserList (42)
#endif

/* struct _ns3__deleteUserRequestParameter has binding name '_ns3__deleteUserRequestParameter' for type '' */
#ifndef SOAP_TYPE__ns3__deleteUserRequestParameter
#define SOAP_TYPE__ns3__deleteUserRequestParameter (40)
#endif

/* struct _ns3__searchUserRequestParameter has binding name '_ns3__searchUserRequestParameter' for type '' */
#ifndef SOAP_TYPE__ns3__searchUserRequestParameter
#define SOAP_TYPE__ns3__searchUserRequestParameter (38)
#endif

/* struct _ns3__createUserRequestParameter has binding name '_ns3__createUserRequestParameter' for type '' */
#ifndef SOAP_TYPE__ns3__createUserRequestParameter
#define SOAP_TYPE__ns3__createUserRequestParameter (36)
#endif

/* struct _ns3__LogoutRequestParameter has binding name '_ns3__LogoutRequestParameter' for type '' */
#ifndef SOAP_TYPE__ns3__LogoutRequestParameter
#define SOAP_TYPE__ns3__LogoutRequestParameter (35)
#endif

/* struct _ns3__LoginImpersonateRequestParameter has binding name '_ns3__LoginImpersonateRequestParameter' for type '' */
#ifndef SOAP_TYPE__ns3__LoginImpersonateRequestParameter
#define SOAP_TYPE__ns3__LoginImpersonateRequestParameter (33)
#endif

/* struct _ns3__LoginSAMLRequestParameter has binding name '_ns3__LoginSAMLRequestParameter' for type '' */
#ifndef SOAP_TYPE__ns3__LoginSAMLRequestParameter
#define SOAP_TYPE__ns3__LoginSAMLRequestParameter (32)
#endif

/* struct _ns3__LoginNoAuthRequestParameter has binding name '_ns3__LoginNoAuthRequestParameter' for type '' */
#ifndef SOAP_TYPE__ns3__LoginNoAuthRequestParameter
#define SOAP_TYPE__ns3__LoginNoAuthRequestParameter (31)
#endif

/* struct _ns3__LoginRequestParameter has binding name '_ns3__LoginRequestParameter' for type '' */
#ifndef SOAP_TYPE__ns3__LoginRequestParameter
#define SOAP_TYPE__ns3__LoginRequestParameter (30)
#endif

/* struct _ns3__session has binding name '_ns3__session' for type '' */
#ifndef SOAP_TYPE__ns3__session
#define SOAP_TYPE__ns3__session (29)
#endif

/* struct ns3__T_USCOREIdList has binding name 'ns3__T_USCOREIdList' for type 'ns3:T_IdList' */
#ifndef SOAP_TYPE_ns3__T_USCOREIdList
#define SOAP_TYPE_ns3__T_USCOREIdList (25)
#endif

/* struct ns3__T_USCOREUser has binding name 'ns3__T_USCOREUser' for type 'ns3:T_User' */
#ifndef SOAP_TYPE_ns3__T_USCOREUser
#define SOAP_TYPE_ns3__T_USCOREUser (24)
#endif

/* struct ns3__UserIDInfo has binding name 'ns3__UserIDInfo' for type 'ns3:UserIDInfo' */
#ifndef SOAP_TYPE_ns3__UserIDInfo
#define SOAP_TYPE_ns3__UserIDInfo (22)
#endif

/* struct ns3__T_USCOREForeignKeyList has binding name 'ns3__T_USCOREForeignKeyList' for type 'ns3:T_ForeignKeyList' */
#ifndef SOAP_TYPE_ns3__T_USCOREForeignKeyList
#define SOAP_TYPE_ns3__T_USCOREForeignKeyList (20)
#endif

/* struct ns3__T_USCOREForeignKey has binding name 'ns3__T_USCOREForeignKey' for type 'ns3:T_ForeignKey' */
#ifndef SOAP_TYPE_ns3__T_USCOREForeignKey
#define SOAP_TYPE_ns3__T_USCOREForeignKey (19)
#endif

/* struct ns2__GeneralWebserviceException has binding name 'ns2__GeneralWebserviceException' for type 'ns2:GeneralWebserviceException' */
#ifndef SOAP_TYPE_ns2__GeneralWebserviceException
#define SOAP_TYPE_ns2__GeneralWebserviceException (18)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (114)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (113)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (110)
#endif

/* struct _ns3__UserList * has binding name 'PointerTo_ns3__UserList' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__UserList
#define SOAP_TYPE_PointerTo_ns3__UserList (105)
#endif

/* struct _ns3__searchUserRequestParameter * has binding name 'PointerTo_ns3__searchUserRequestParameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__searchUserRequestParameter
#define SOAP_TYPE_PointerTo_ns3__searchUserRequestParameter (104)
#endif

/* struct __ns1__deleteUserResponse * has binding name 'PointerTo__ns1__deleteUserResponse' for type '-ns1:deleteUserResponse' */
#ifndef SOAP_TYPE_PointerTo__ns1__deleteUserResponse
#define SOAP_TYPE_PointerTo__ns1__deleteUserResponse (101)
#endif

/* struct _ns3__deleteUserRequestParameter * has binding name 'PointerTo_ns3__deleteUserRequestParameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__deleteUserRequestParameter
#define SOAP_TYPE_PointerTo_ns3__deleteUserRequestParameter (100)
#endif

/* struct _ns3__createUserRequestParameter * has binding name 'PointerTo_ns3__createUserRequestParameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__createUserRequestParameter
#define SOAP_TYPE_PointerTo_ns3__createUserRequestParameter (96)
#endif

/* struct __ns1__LogoutResponse * has binding name 'PointerTo__ns1__LogoutResponse' for type '-ns1:LogoutResponse' */
#ifndef SOAP_TYPE_PointerTo__ns1__LogoutResponse
#define SOAP_TYPE_PointerTo__ns1__LogoutResponse (93)
#endif

/* struct _ns3__LogoutRequestParameter * has binding name 'PointerTo_ns3__LogoutRequestParameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__LogoutRequestParameter
#define SOAP_TYPE_PointerTo_ns3__LogoutRequestParameter (92)
#endif

/* struct _ns3__LoginImpersonateRequestParameter * has binding name 'PointerTo_ns3__LoginImpersonateRequestParameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__LoginImpersonateRequestParameter
#define SOAP_TYPE_PointerTo_ns3__LoginImpersonateRequestParameter (88)
#endif

/* struct _ns3__LoginSAMLRequestParameter * has binding name 'PointerTo_ns3__LoginSAMLRequestParameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__LoginSAMLRequestParameter
#define SOAP_TYPE_PointerTo_ns3__LoginSAMLRequestParameter (85)
#endif

/* struct _ns3__LoginNoAuthRequestParameter * has binding name 'PointerTo_ns3__LoginNoAuthRequestParameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__LoginNoAuthRequestParameter
#define SOAP_TYPE_PointerTo_ns3__LoginNoAuthRequestParameter (82)
#endif

/* struct _ns3__session * has binding name 'PointerTo_ns3__session' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__session
#define SOAP_TYPE_PointerTo_ns3__session (79)
#endif

/* struct _ns3__LoginRequestParameter * has binding name 'PointerTo_ns3__LoginRequestParameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__LoginRequestParameter
#define SOAP_TYPE_PointerTo_ns3__LoginRequestParameter (78)
#endif

/* struct _ns2__ServerMaintenanceException * has binding name 'PointerTo_ns2__ServerMaintenanceException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__ServerMaintenanceException
#define SOAP_TYPE_PointerTo_ns2__ServerMaintenanceException (75)
#endif

/* struct _ns2__PermissionDeniedException * has binding name 'PointerTo_ns2__PermissionDeniedException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__PermissionDeniedException
#define SOAP_TYPE_PointerTo_ns2__PermissionDeniedException (74)
#endif

/* struct _ns2__InvalidUsernamePasswordCombinationException * has binding name 'PointerTo_ns2__InvalidUsernamePasswordCombinationException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidUsernamePasswordCombinationException
#define SOAP_TYPE_PointerTo_ns2__InvalidUsernamePasswordCombinationException (73)
#endif

/* struct _ns2__InvalidUsernameException * has binding name 'PointerTo_ns2__InvalidUsernameException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidUsernameException
#define SOAP_TYPE_PointerTo_ns2__InvalidUsernameException (72)
#endif

/* struct _ns2__InvalidSessionException * has binding name 'PointerTo_ns2__InvalidSessionException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidSessionException
#define SOAP_TYPE_PointerTo_ns2__InvalidSessionException (71)
#endif

/* struct _ns2__InvalidParameterException * has binding name 'PointerTo_ns2__InvalidParameterException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidParameterException
#define SOAP_TYPE_PointerTo_ns2__InvalidParameterException (70)
#endif

/* struct _ns2__InvalidNrOfImpersonationsException * has binding name 'PointerTo_ns2__InvalidNrOfImpersonationsException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidNrOfImpersonationsException
#define SOAP_TYPE_PointerTo_ns2__InvalidNrOfImpersonationsException (69)
#endif

/* struct _ns2__InvalidNamedLicenseException * has binding name 'PointerTo_ns2__InvalidNamedLicenseException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidNamedLicenseException
#define SOAP_TYPE_PointerTo_ns2__InvalidNamedLicenseException (68)
#endif

/* struct _ns2__InvalidDatesException * has binding name 'PointerTo_ns2__InvalidDatesException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidDatesException
#define SOAP_TYPE_PointerTo_ns2__InvalidDatesException (67)
#endif

/* struct _ns2__InvalidConcurrentLicenseException * has binding name 'PointerTo_ns2__InvalidConcurrentLicenseException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidConcurrentLicenseException
#define SOAP_TYPE_PointerTo_ns2__InvalidConcurrentLicenseException (66)
#endif

/* struct _ns2__InvalidClientException * has binding name 'PointerTo_ns2__InvalidClientException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__InvalidClientException
#define SOAP_TYPE_PointerTo_ns2__InvalidClientException (65)
#endif

/* struct _ns2__ImpersonatedUserNotFoundException * has binding name 'PointerTo_ns2__ImpersonatedUserNotFoundException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__ImpersonatedUserNotFoundException
#define SOAP_TYPE_PointerTo_ns2__ImpersonatedUserNotFoundException (64)
#endif

/* struct _ns2__GeneralWebserviceException * has binding name 'PointerTo_ns2__GeneralWebserviceException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__GeneralWebserviceException
#define SOAP_TYPE_PointerTo_ns2__GeneralWebserviceException (63)
#endif

/* struct _ns2__AssertionException * has binding name 'PointerTo_ns2__AssertionException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns2__AssertionException
#define SOAP_TYPE_PointerTo_ns2__AssertionException (62)
#endif

/* struct ns3__T_USCOREUser * has binding name 'PointerTons3__T_USCOREUser' for type 'ns3:T_User' */
#ifndef SOAP_TYPE_PointerTons3__T_USCOREUser
#define SOAP_TYPE_PointerTons3__T_USCOREUser (43)
#endif

/* struct ns3__UserIDInfo * has binding name 'PointerTons3__UserIDInfo' for type 'ns3:UserIDInfo' */
#ifndef SOAP_TYPE_PointerTons3__UserIDInfo
#define SOAP_TYPE_PointerTons3__UserIDInfo (41)
#endif

/* enum ns3__T_USCOREUserState * has binding name 'PointerTons3__T_USCOREUserState' for type 'ns3:T_UserState' */
#ifndef SOAP_TYPE_PointerTons3__T_USCOREUserState
#define SOAP_TYPE_PointerTons3__T_USCOREUserState (39)
#endif

/* enum ns3__T_USCORELicenseType * has binding name 'PointerTons3__T_USCORELicenseType' for type 'ns3:T_LicenseType' */
#ifndef SOAP_TYPE_PointerTons3__T_USCORELicenseType
#define SOAP_TYPE_PointerTons3__T_USCORELicenseType (37)
#endif

/* LONG64 * has binding name 'PointerTons3__id' for type 'ns3:id' */
#ifndef SOAP_TYPE_PointerTons3__id
#define SOAP_TYPE_PointerTons3__id (28)
#endif

/* struct ns3__T_USCOREForeignKeyList * has binding name 'PointerTons3__T_USCOREForeignKeyList' for type 'ns3:T_ForeignKeyList' */
#ifndef SOAP_TYPE_PointerTons3__T_USCOREForeignKeyList
#define SOAP_TYPE_PointerTons3__T_USCOREForeignKeyList (27)
#endif

/* struct ns3__T_USCOREIdList * has binding name 'PointerTons3__T_USCOREIdList' for type 'ns3:T_IdList' */
#ifndef SOAP_TYPE_PointerTons3__T_USCOREIdList
#define SOAP_TYPE_PointerTons3__T_USCOREIdList (26)
#endif

/* struct ns3__T_USCOREForeignKey * has binding name 'PointerTons3__T_USCOREForeignKey' for type 'ns3:T_ForeignKey' */
#ifndef SOAP_TYPE_PointerTons3__T_USCOREForeignKey
#define SOAP_TYPE_PointerTons3__T_USCOREForeignKey (21)
#endif

/* xsd__date has binding name 'xsd__date' for type 'xsd:date' */
#ifndef SOAP_TYPE_xsd__date
#define SOAP_TYPE_xsd__date (8)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Login(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__LoginRequestParameter *ns3__LoginRequestParameter, struct _ns3__session *ns3__session);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__LoginNoAuth(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__LoginNoAuthRequestParameter *ns3__LoginNoAuthRequestParameter, struct _ns3__session *ns3__session);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__LoginSAML(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__LoginSAMLRequestParameter *ns3__LoginSAMLRequestParameter, struct _ns3__session *ns3__session);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__LoginImpersonate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__LoginImpersonateRequestParameter *ns3__LoginImpersonateRequestParameter, struct _ns3__session *ns3__session);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__LogoutRequestParameter *ns3__LogoutRequestParameter, struct __ns1__LogoutResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__createUserRequestParameter *ns3__createUserRequestParameter, struct ns3__T_USCOREUser *ns3__User);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__deleteUserRequestParameter *ns3__deleteUserRequestParameter, struct __ns1__deleteUserResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__searchUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__searchUserRequestParameter *ns3__searchUserRequestParameter, struct _ns3__UserList *ns3__UserList);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
